schema_version: 20180708
name: flow
version: 0.0.69
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk9-1.0.83
run_image: fnproject/fn-java-fdk:jdk9-1.0.83
cmd: com.example.fn.FlowFunction::handleRequest
idle_timeout: 3600
triggers:
- name: flow
  type: http
  source: /flow
